



user_home_dir := `realpath ~`

viper_tools := user_home_dir / "software/VSCodium-linux-x64-1.80.1.23194/data/user-data/User/globalStorage/viper-admin.viper/Stable/ViperTools"


export Z3_EXE := viper_tools / "z3/bin/z3"
export BOOGIE_EXE := viper_tools / "boogie/Binaries/Boogie"

classfile_dir_candidate_1 := user_home_dir / "software/VSCodium-linux-x64-1.80.1.23194/data/user-data/User/globalStorage/viper-admin.viper/Stable/ViperTools/backends"
classfile_dir_candidate_2 := user_home_dir / ".config/VSCodium/User/globalStorage/viper-admin.viper/Stable/ViperTools/backends/"

#viper_backend := "viper.silicon.SiliconRunner"
viper_backend := "viper.carbon.Carbon"


classfile_dir := if path_exists(classfile_dir_candidate_1) == "true" {
        classfile_dir_candidate_1
    } else if path_exists(classfile_dir_candidate_2) == "true" {
        classfile_dir_candidate_2
    } else {
        error("None of the classfile dirs exists")
    }



_default:
  @just --list --unsorted


list_classes:
  jar tvf "{{classfile_dir}}/viperserver.jar"

run_viper_with_extension file:
  java -Xmx2048m -Xss128m \
    -cp :"{{classfile_dir}}/silver-sif-extension.jar":"{{classfile_dir}}/viperserver.jar" "{{viper_backend}}" \
    --plugin viper.silver.sif.SIFPlugin {{file}}
